name: Run Bot Creator

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # يعيد التشغيل كل 5 دقائق

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python bot_creator.py
